name: Publish

on:
  push:
    tags:
      - v*

jobs:
  images:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        base-image:
          - quay.io/kairos/core-opensuse-leap:v2.1.3
          - quay.io/kairos/core-ubuntu-20-lts:v2.1.3
          - quay.io/kairos/core-ubuntu-22-lts:v2.1.3
        kubeadm-version:
          - 1.22.15
          - 1.23.12
          - 1.24.6
          - 1.25.2
          - 1.26.4
    env:
      REGISTRY: quay.io
      REGISTRY_USER: ${{ secrets.QUAY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - uses: earthly/actions-setup@v1
        with:
          version: "v0.6.30"
      - run: echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin $REGISTRY
      - run: env | grep ACTIONS_ID_TOKEN_REQUEST > .env
      - run: env | grep REGISTRY >> .env
      - run: earthly --ci --push +docker-all-platforms --KUBEADM_VERSION=${{ matrix.kubeadm-version }} --BASE_IMAGE=${{ matrix.base-image }}
      - run: earthly --ci +cosign-all-platforms --KUBEADM_VERSION=${{ matrix.kubeadm-version }} --BASE_IMAGE=${{ matrix.base-image }}
  images-fips:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        base-image:
          - quay.io/kairos/core-opensuse-leap:v2.1.3
          - quay.io/kairos/core-ubuntu-20-lts:v2.1.3
          - quay.io/kairos/core-ubuntu-22-lts:v2.1.3
        kubeadm-version:
          - 1.22.15
          - 1.23.12
          - 1.24.6
          - 1.25.2
          - 1.24.13
          - 1.25.9
          - 1.26.4
    env:
      REGISTRY: quay.io
      REGISTRY_USER: ${{ secrets.QUAY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - uses: earthly/actions-setup@v1
        with:
          version: "v0.6.30"
      - run: echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin $REGISTRY
      - run: env | grep ACTIONS_ID_TOKEN_REQUEST > .env
      - run: env | grep REGISTRY >> .env
      - run: earthly --ci --push +docker-all-platforms --KUBEADM_VERSION=${{ matrix.kubeadm-version }} --BASE_IMAGE=${{ matrix.base-image }} --FIPS_ENABLED=true
      - run: earthly --ci +cosign-all-platforms --KUBEADM_VERSION=${{ matrix.kubeadm-version }} --BASE_IMAGE=${{ matrix.base-image }} --FIPS_ENABLED=true

