name: Pull Request

on:
  pull_request:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - run: earthly --ci +lint
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        base-image:
          - quay.io/kairos/core-opensuse:v1.1.6
          - quay.io/kairos/core-ubuntu-20-lts:v1.1.6
          - quay.io/kairos/core-ubuntu-22-lts:v1.1.6
        kubeadm-version:
          - v1.22.15
          - v1.23.12
          - v1.24.6
          - v1.25.2
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - run: earthly --ci +docker-all-platforms --KUBEADM_VERSION=${{ matrix.kubeadm-version }} --BASE_IMAGE=${{ matrix.base-image }}
