name: Pull Request

on:
  pull_request:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - uses: earthly/actions-setup@v1
        with:
          version: "v0.6.30"
      - run: earthly --ci +lint
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        base-image:
          - quay.io/kairos/core-opensuse-leap:v1.6.0
          - quay.io/kairos/core-ubuntu-20-lts:v1.6.0
          - quay.io/kairos/core-ubuntu-22-lts:v1.6.0
        kubeadm-version:
          - 1.24.6
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - uses: earthly/actions-setup@v1
        with:
          version: "v0.6.30"
      - run: earthly --ci +docker-all-platforms --KUBEADM_VERSION=${{ matrix.kubeadm-version }} --BASE_IMAGE=${{ matrix.base-image }}
  build-fips:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        base-image:
          - quay.io/kairos/core-opensuse-leap:v1.6.0
          - quay.io/kairos/core-ubuntu-20-lts:v1.6.0
          - quay.io/kairos/core-ubuntu-22-lts:v1.6.0
        kubeadm-version:
          - 1.24.6
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - uses: earthly/actions-setup@v1
        with:
          version: "v0.6.30"
      - run: earthly --ci +docker-all-platforms --KUBEADM_VERSION=${{ matrix.kubeadm-version }} --BASE_IMAGE=${{ matrix.base-image }} --FIPS_ENABLED=true
